name: retrieval
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/rohanchandra/retrieval
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  characters: ^1.1.0
dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
