name: retrieval
description: A trie data structure Dart implementation — useful for autocomplete.
version: 1.0.1
repository: https://github.com/rohanchandra/retrieval.dart
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  characters: ^1.1.0
dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
